apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # List all components that form the infrastructure for this cluster
  - ./ingress-nginx
  - ./cert-manager
  # Add other infrastructure components here as they are created (e.g., ./external-secrets-operator) 