apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager # Ensure resources from this overlay are in the cert-manager namespace
resources:
  - ../../../../../bases/cert-manager # Adjusted path to base

# Patches for dev-specific values can be added here if needed. 