apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../bases/ingress-nginx # Path to the base

# Example of a patch for dev-specific values (if needed):
# patches:
#  - patch: |-
#      - op: replace
#        path: /spec/values/controller/replicaCount
#        value: 1 # Override replicaCount for dev
#    target:
#      kind: HelmRelease
#      name: ingress-nginx
#      namespace: ingress-nginx 