apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mimir-write
  namespace: observability-mimir
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx-internal
  rules:
  - host: mimir.platform-core.internal
    http:
      paths:
      - path: /api/v1/push
        pathType: Prefix
        backend:
          service:
            name: mimir-write # The monolithic chart creates a 'mimir-write' service target
            port:
              number: 8080
