apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # List all ClusterIssuer overlays for this cluster
  - ./letsencrypt-staging
  # - ./letsencrypt-prod # Example for when you add a production issuer 