apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../../bases/cluster-issuers/letsencrypt-staging

# Example patch if you need to change the email for the dev cluster's staging issuer:
# patches:
#  - patch: |-
#      - op: replace
#        path: /spec/acme/email
#        value: dev-admin@platformcore.com
#    target:
#      kind: ClusterIssuer
#      name: letsencrypt-staging 