apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../../bases/cluster-issuers/letsencrypt-staging

# Example patch to change the email for the staging issuer specifically for this dev cluster:
# patches:
#  - patch: |-
#      - op: replace
#        path: /spec/acme/email
#        value: dev-cluster-admin@example.com
#    target:
#      kind: ClusterIssuer
#      name: letsencrypt-staging 