apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-creds
  namespace: observability-grafana
spec:
  secretStoreRef:
    name: dev-akv-secretstore # Assumes a ClusterSecretStore named this exists
    kind: ClusterSecretStore
  target:
    name: grafana-admin-secret
    creationPolicy: Owner
  data:
  - secretKey: admin-user
    remoteRef:
      key: grafana-admin-user # Assumes this secret exists in AKV
  - secretKey: admin-password
    remoteRef:
      key: ops-uaenorth-grafana-admin-password
