apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespaces
  - ./helm-repositories
  - ./components
  - ./cluster-issuers
  - ./secret-stores
  - ./observability
  # Add other infrastructure categories here if any 